### PR TITLE
Allow inline multiple substitutions, fixes #99

### LINKED ISSUE #99: support chain sub rules with inline multiple sub statements
Similar to #98; fonttools supports this, but it is not part of the spec.

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Review by cmyr — COMMENTED** [review]
Cool, thanks for taking this on!

This looks good, but I think the one good thing to add would be some tests; specifically I would add a parse in `test-data/parse/good` that included multiple substitutions, and I would include a compile test (`test-data/compile/mini-latin/bad`) that checked that compilation fails if there is a multi-sub rule with a class target.

I played around with this, and the two files were,

(good)
```fea
lookup hi {
    substitute [ a e i o u] f_f' by f f;
} hi;
```

and (bad)

```fea
lookup hi {
    substitute [ a e i o u] [f_f f_f_i]' by f f;
} hi;
```

The former needs to be a compile test and not a parse test since we don't check this error until we're actually compiling.
 
Once the files are added, you rebuild the expected outputs by setting `FEA_WRITE_TEST_OUTPUT=1` when running cargo test. The various subdirectories under `test-data` should have `README.md` files explaining how they work.

oh, one last headache: the test data is in its own repo, which is a submodule here. that repo is at https://github.com/cmyr/fea-rs-test-data; so PR the new test files there, then update the submodule in this PR, and we can merge.

**Comment by cmyr** [comment]
@simoncozens cool, the tests look good, now you just need to commit the updated submodule in this repo and we can merge :)

**Comment by cmyr** [comment]
I'm going to merge this and then update the submodule in a separate commit.

**Comment by simoncozens** [comment]
Thank you! I would have got around to this but ATypI intervened...

**Pull request merged**
